#pragma once
#ifndef __CONST_H__
#define __CONST_H__

#define POWER_INCREASE 600
#define MONEY_INCREASE 20

#define INITIAL_POWER 600
#define INITIAL_MONEY 1000000

#define MINE_MONEY 2000
#define POWER_PLANT_MONEY 2000
#define TANK_FACTARY_MONEY 2000
#define MILITARY_CAMP_MONEY 2000

#define BUILDING_CONSUME_POWER 200

#define BOX_EDGE_WITDH_SMALL 10
#define BOX_EDGE_WITDH 40
#define SCROLL_LENGTH 10

#define PATH_FINDING_TERMINAL 3
#define REFIND_PATH_MAX_RANGE 30.f

#define FIGHTER_PERIOD 0
#define SOLDIER_PERIOD 50
#define TANK_PERIOD 150
#define MILITARY_PERIOD 180
#define MINE_PERIOD 180
#define TANKFACTARY_PERIOD 180
#define POWERPLANT_PERIOD 180
#endif // !__CONST_H__

